apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance-app
  template:
    metadata:
      labels:
        app: insurance-app
    spec:
      containers:
      - name: insurance-container
        image: abhisdockerhub/insurance-app:latest  # This will be replaced in pipeline
        ports:
        - containerPort: 8081
