apiVersion: v1
kind: Service
metadata:
  name: insurance-service
spec:
  selector:
    app: insurance-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000   # Force NodePort to be 8081 (must be in range 30000–32767 unless you change kubelet config)
  type: NodePort
